"""Auto-apply honest-pipeline semantics (UX-quality session).

The queue used to be a silent dead-end. Pins the new contract:
- queued jobs with missing docs get them GENERATED by the cron;
- auto-apply OFF → docs prepared + handed to the user (READY_TO_SUBMIT),
  never a silent skip;
- boards without a real submit adapter → READY_TO_SUBMIT with a reason;
- dry-run stamps + hands over instead of re-stamping forever;
- submission failure hands over with the failure message;
- auto_apply_phase computes the UI chip for every pipeline stage.
"""

from __future__ import annotations

from datetime import UTC, datetime
from types import SimpleNamespace
from unittest.mock import AsyncMock, patch

import pytest

from models import ApplicationBoard, ApplicationStatus, DocsState, JobQueueState
from services.application_service import (
    AutoApplyResult,
    auto_apply_phase,
    process_auto_apply_queue,
)
from services.ats import board_supports_auto_submit

# Reuse the canonical fakes from the application-service suite.
from tests.test_application_service import (
    _exec_all,
    _exec_count,
    _exec_one,
    _FakeSession,
    _make_app,
    _make_job,
)


def _settings(**kw):
    base = {
        "user_id": 1,
        "auto_apply_enabled": True,
        "auto_apply_daily_cap": None,
        "auto_apply_score_threshold": 0.7,
        "auto_apply_per_board_daily_caps": {},
        "auto_apply_dry_run": False,
    }
    base.update(kw)
    return SimpleNamespace(**base)


def test_supported_boards_are_the_three_http_adapters():
    assert board_supports_auto_submit(ApplicationBoard.GREENHOUSE)
    assert board_supports_auto_submit(ApplicationBoard.LEVER)
    assert board_supports_auto_submit(ApplicationBoard.ASHBY)
    for board in (
        ApplicationBoard.LINKEDIN,
        ApplicationBoard.INDEED,
        ApplicationBoard.WORKDAY,
        ApplicationBoard.COMPANY_DIRECT,
        ApplicationBoard.MANUAL,
    ):
        assert not board_supports_auto_submit(board)
    assert not board_supports_auto_submit(None)


@pytest.mark.asyncio
async def test_queue_generates_docs_when_missing():
    """docs_state NONE → the cron generates the bundle instead of skipping."""
    app_row = _make_app(docs_state=DocsState.NONE)
    job_row = _make_job(queue_state=JobQueueState.QUEUED_FOR_AUTO_APPLY, score=0.9)
    session = _FakeSession()
    session.exec_queue = [_exec_all([(app_row, job_row)]), _exec_one(_settings())]

    async def fake_generate(sess, application, *, settings, job=None):
        application.docs_state = DocsState.READY
        return SimpleNamespace(skipped_reason=None, degraded=False)

    fake_submit = AsyncMock(
        return_value=_make_app(status=ApplicationStatus.APPLIED, applied_at=datetime.now(UTC))
    )
    with (
        patch("services.generation.generate_bundle", new=fake_generate),
        patch("services.application_service.submit_draft", new=fake_submit),
    ):
        result = await process_auto_apply_queue(session)

    assert result.docs_generated == 1
    assert result.submitted == 1
    blob = (app_row.submission_artifacts or {}).get("auto_apply") or {}
    assert blob.get("docs_ready_at")


@pytest.mark.asyncio
async def test_disabled_hands_docs_ready_job_to_user():
    """auto_apply_enabled=False no longer silently skips — the job flips to
    READY_TO_SUBMIT with a reason."""
    app_row = _make_app(docs_state=DocsState.READY)
    job_row = _make_job(queue_state=JobQueueState.QUEUED_FOR_AUTO_APPLY, score=0.9)
    session = _FakeSession()
    session.exec_queue = [
        _exec_all([(app_row, job_row)]),
        _exec_one(_settings(auto_apply_enabled=False)),
    ]
    result = await process_auto_apply_queue(session)
    assert result.handed_to_user == 1
    assert job_row.queue_state == JobQueueState.READY_TO_SUBMIT
    blob = (app_row.submission_artifacts or {}).get("auto_apply") or {}
    assert "auto-apply is off" in (blob.get("needs_you_reason") or "")


@pytest.mark.asyncio
async def test_unsupported_board_hands_to_user_with_reason():
    app_row = _make_app(docs_state=DocsState.READY, board=ApplicationBoard.LINKEDIN)
    job_row = _make_job(
        queue_state=JobQueueState.QUEUED_FOR_AUTO_APPLY,
        score=0.9,
        board=ApplicationBoard.LINKEDIN,
    )
    session = _FakeSession()
    session.exec_queue = [_exec_all([(app_row, job_row)]), _exec_one(_settings())]
    fake_submit = AsyncMock()
    with patch("services.application_service.submit_draft", new=fake_submit):
        result = await process_auto_apply_queue(session)
    fake_submit.assert_not_awaited()
    assert result.handed_to_user == 1
    assert job_row.queue_state == JobQueueState.READY_TO_SUBMIT
    blob = (app_row.submission_artifacts or {}).get("auto_apply") or {}
    assert "linkedin" in (blob.get("needs_you_reason") or "")


@pytest.mark.asyncio
async def test_dry_run_hands_over_instead_of_requeueing_forever():
    app_row = _make_app(docs_state=DocsState.READY)
    job_row = _make_job(queue_state=JobQueueState.QUEUED_FOR_AUTO_APPLY, score=0.9)
    session = _FakeSession()
    session.exec_queue = [
        _exec_all([(app_row, job_row)]),
        _exec_one(_settings(auto_apply_dry_run=True)),
        _exec_count(0),  # validate: screener count
        _exec_one(None),  # validate: sponsorship profile
    ]
    # Item 7: dry-run now calls submit_draft(dry_run=True) for real
    # filled-form evidence; the stamp happens inside submit_draft (mocked
    # here), and the hand-off still fires afterwards.
    fake_submit = AsyncMock(return_value=app_row)
    with patch("services.application_service.submit_draft", new=fake_submit):
        result = await process_auto_apply_queue(session)
    fake_submit.assert_awaited_once()
    assert fake_submit.await_args.kwargs.get("dry_run") is True
    assert result.handed_to_user == 1
    assert job_row.queue_state == JobQueueState.READY_TO_SUBMIT


@pytest.mark.asyncio
async def test_submission_failure_hands_over_with_message():
    app_row = _make_app(
        docs_state=DocsState.READY,
        submission_artifacts={"last_failure": {"kind": "captcha", "message": "CAPTCHA wall"}},
    )
    job_row = _make_job(queue_state=JobQueueState.QUEUED_FOR_AUTO_APPLY, score=0.9)
    session = _FakeSession()
    session.exec_queue = [
        _exec_all([(app_row, job_row)]),
        _exec_one(_settings()),
        _exec_count(0),
        _exec_one(None),
    ]
    # submit_draft returns the app still in DRAFT (failure path).
    fake_submit = AsyncMock(return_value=app_row)
    with patch("services.application_service.submit_draft", new=fake_submit):
        result = await process_auto_apply_queue(session)
    assert result.failed == 1
    assert result.handed_to_user == 1
    assert job_row.queue_state == JobQueueState.READY_TO_SUBMIT
    blob = (app_row.submission_artifacts or {}).get("auto_apply") or {}
    assert "CAPTCHA wall" in (blob.get("needs_you_reason") or "")


def test_auto_apply_phase_covers_the_pipeline():
    job_q = _make_job(queue_state=JobQueueState.QUEUED_FOR_AUTO_APPLY)
    assert auto_apply_phase(_make_app(docs_state=DocsState.GENERATING), job_q)["phase"] == (
        "generating"
    )
    assert auto_apply_phase(_make_app(docs_state=DocsState.READY), job_q)["phase"] == "docs_ready"
    assert auto_apply_phase(_make_app(docs_state=DocsState.NONE), job_q)["phase"] == "queued"

    job_ready = _make_job(queue_state=JobQueueState.READY_TO_SUBMIT)
    app_ready = _make_app(
        docs_state=DocsState.READY,
        submission_artifacts={"auto_apply": {"needs_you_reason": "no adapter"}},
    )
    phase = auto_apply_phase(app_ready, job_ready)
    assert phase["phase"] == "needs_you"
    assert phase["reason"] == "no adapter"

    job_applied = _make_job(queue_state=JobQueueState.APPLIED)
    app_applied = _make_app(status=ApplicationStatus.APPLIED, applied_at=datetime.now(UTC))
    assert auto_apply_phase(app_applied, job_applied)["phase"] == "submitted"

    assert auto_apply_phase(None, job_q) is None
    assert auto_apply_phase(_make_app(), _make_job(queue_state=JobQueueState.UNSWIPED)) is None


def test_auto_apply_result_new_counters_default_zero():
    r = AutoApplyResult()
    assert r.docs_generated == 0
    assert r.handed_to_user == 0
